package ru.otus.hw16.changesets;

import com.github.cloudyrock.mongock.ChangeLog;
import com.github.cloudyrock.mongock.ChangeSet;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ru.otus.hw16.domain.ChatMessage;


@ChangeLog
public class ChatMessageSets {

    private static final String COLLECTION_NAME = "chatMessage";
    private static final Logger logger = LoggerFactory.getLogger(ChatMessageSets.class);


    @ChangeSet(id= "withMongoDatabase04", order = "001", author = "Mongock")
    public void changeSet1(MongoDatabase mongoDatabase) {
        mongoDatabase.getCollection(COLLECTION_NAME).insertOne(createMongoDocument(getChatMessage(ChatMessage.MessageType.CHAT, "Welcome to chat with MS", "Mongock")));
    }

    @ChangeSet(id= "withMongoDatabase05", order = "002", author = "Mongock")
    public void changeSet2(MongoDatabase mongoDatabase) {
        mongoDatabase.getCollection(COLLECTION_NAME).insertOne(createMongoDocument(getChatMessage(ChatMessage.MessageType.CHAT, "These messages are generated by default.", "Mongock")));
    }

    private Document createMongoDocument(ChatMessage chatMessage) {
        Document document =  new Document()
                .append("type", chatMessage.getType())
                .append("sender", chatMessage.getSender())
                .append("content", chatMessage.getContent()
                );
        logger.debug(document.toString());
        return document;
}

    private ChatMessage getChatMessage(ChatMessage.MessageType type, String content, String sender) {
        return new ChatMessage(type,content,sender);
    }
}
